### ISSUE TITLE
Signing up doesn't work

### ISSUE THREAD

**Issue by shllshckd** [popovgeorgi/BeatsWaveNOIT#15]
Maybe I am doing something wrong, but when I try to sign up with new account, providing valid data and then proceeding to log in it actually doesn't let me in. Could you look it up? The application looks great from the demo so I consider using it on a daily basis. :)
Edit: it appears to be a mobile-only thing, because I was able to register from a desktop PC.

**Comment by popovgeorgi** [comment]
Hi @shllshckd!
Thank you for your interest!
Keep in mind that your password is stored as a **hash**, so the casing of the letters really matters and that should be your case. It doesn't matter whether you are accessing the website via mobile or desktop as it is using the same services.
